language: php

branches:
  only:
    - master
    - develop

php:
  - 7
  - 7.1
  - 7.2

before_script:
  - composer self-update
  - composer install --no-interaction

script:
  - mkdir build
  - composer check

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/clover.xml

sudo: false
