language: php

branches:
  only:
    - /.*/

matrix:
  include:
    - php: 7.1
      env:
        - DEPS=lowest
    - php: 7.1
      env:
        - DEPS=latest
    - php: 7.2
      env:
        - DEPS=lowest
    - php: 7.2
      env:
        - DEPS=latest

before_script:
  - composer self-update
  - composer install --no-interaction
  - if [[ $DEPS == 'latest' ]]; then composer update --no-interaction ; fi
  - if [[ $DEPS == 'lowest' ]]; then composer update --no-interaction --prefer-lowest --prefer-stable ; fi
  - composer show

script:
  - mkdir build
  - if [[ $DEPS == 'latest' ]]; then composer ac:ci ; fi
  - if [[ $DEPS == 'lowest' ]]; then composer ac:test ; fi

after_script:
  - if [[ $DEPS == 'latest' ]]; then wget https://scrutinizer-ci.com/ocular.phar ; fi
  - if [[ $DEPS == 'latest' ]]; then php ocular.phar code-coverage:upload --format=php-clover build/clover.xml ; fi

sudo: false
